server:
  port: 10000
  tomcat:
    accept-count: 1000
    max-threads: 1000
    max-connections: 2000
zuul:
  host:
    max-per-route-connections: 1000
    max-total-connections: 1000
spring:
  application:
    name: api-gatway
  datasource:
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.jdbc.Driver
         url: jdbc:mysql://rm-wz9ngn9g3bmdy26yico.mysql.rds.aliyuncs.com/cloud_gateway?useUnicode=true&characterEncoding=utf-8
         username: houzeyu
         password: hzy947126!@#
         filters: stat
         maxActive: 20
         initialSize: 1
         maxWait: 60000
         minIdle: 1
         timeBetweenEvictionRunsMillis: 60000
         minEvictableIdleTimeMillis: 300000
         validationQuery: select 'x'
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         poolPreparedSratements: true
         maxOpenPreparedStatements: 20
  redis:
    cluster:
      nodes:
      - 47.102.46.47:7000
      - 47.102.46.47:7001
      - 139.159.192.84:7000
      - 139.159.192.84:7001
      - 139.9.168.54:7000
      - 139.9.168.54:7001
      max-redirects: 5
    password: hzy947126117.
    lettuce:
      pool:
         # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1ms
    timeout: 60000ms
ribbon:
  ConnectTimeout: 25000 # 连接超时时间(ms)
  ReadTimeout: 20000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 5 # 同一服务不同实例的重试次数
  MaxAutoRetries: 5 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 20000 # 熔断超时时长：10000ms
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
eureka:
  client:
    healthcheck:
      enabled: false
gateway:
    group:  cloudmall-api-gateway
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml
