server:
  port: 10010
spring:
  application:
    name: api-gatway
  datasource:
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.jdbc.Driver
         url: jdbc:mysql://rm-wz9ngn9g3bmdy26yico.mysql.rds.aliyuncs.com/cloud_gateway?useUnicode=true&characterEncoding=utf-8
         username: houzeyu
         password: hzy947126!@#
         filters: stat
         maxActive: 20
         initialSize: 1
         maxWait: 60000
         minIdle: 1
         timeBetweenEvictionRunsMillis: 60000
         minEvictableIdleTimeMillis: 300000
         validationQuery: select 'x'
         testWhileIdle: true
         testOnBorrow: false
         testOnReturn: false
         poolPreparedSratements: true
         maxOpenPreparedStatements: 20
zuul:
  prefix: /api
  retryable: true
ribbon:
  ConnectTimeout: 25000 # 连接超时时间(ms)
  ReadTimeout: 20000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 5 # 同一服务不同实例的重试次数
  MaxAutoRetries: 5 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 20000 # 熔断超时时长：10000ms
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
eureka:
  client:
    healthcheck:
      enabled: false
gateway:
    group:  cloudmall-api-gateway
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml

